### ISSUE TITLE
The page should have fixed padding

### ISSUE THREAD

**Issue by sohrab-** [labeleven-dev/bettercallsol#55]
### What happened?

At the moment, if we reduce the height of the page, it also shrinks the padding at the bottom.

You can essentially obscure the logs at the bottom with the footer if the height is small enough.

![image](https://user-images.githubusercontent.com/4444588/185338187-82ff5877-06ff-412e-8bda-1fb76167dfb2.png)

This is probably due to the percentage-based heights we set in `App.tsx`.

### App Version

v1.0.0-alpha.37

### Web Browser

All

**Comment by josephlabeleven** [comment]
resolved by #67
