### ISSUE TITLE
Allow to clone from an existing transaction

### ISSUE THREAD

**Issue by y2kappa** [labeleven-dev/bettercallsol#95]

**Comment by sohrab-** [comment]
If you click on the "Import" button at the top right, you can provide an existing transaction ID and load one or more (or all) of its instructions into your transaction.

![image](https://user-images.githubusercontent.com/4444588/208321777-39426742-da1c-44ea-8780-5f51dc635cd2.png)

Please re-open this issue if this is not what you meant.
