### ISSUE TITLE
If input program has IDL, then allow the instruction data to prepopulate sighash + arguments from the IDL

### ISSUE THREAD

**Issue by y2kappa** [labeleven-dev/bettercallsol#96]

**Comment by sohrab-** [comment]
Related: #40 and #93

**Comment by sohrab-** [comment]
The tool now detects Anchor programs and lets you pick an instruction to load in.

![Feb-07-2023 11-33-23](https://user-images.githubusercontent.com/4444588/217118190-b6754471-bbcc-46fd-8530-81827ef87691.gif)

Also when importing a transaction from the chain, it detects the Anchor program _and_ the instruction and will let you attempt to convert it.
